openapi: 3.0.0
info:
  version: 1.0-oas3
  title: cpuinfo
  description: >-
    A simple service to get cpuinfo as an example of using swagger-2.0
    specification and codegen
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
paths:
 
  /predict/<arg1>/<arg2>/<arg3>/<arg4>/<arg5>/<arg6>/<arg7>/<arg8>/<arg9>/<arg10>/<arg11>/
	<arg12>/<arg13>/<arg14>/<arg15>/<arg16>/<arg17>/<arg18>/<arg19>/<arg20>/<arg21>:
    get:
      tags:
        - Predict
      operationId: project/predict.predict
      parameters:
          required: true
      description: gets information through predict about fetal patient, rus model
      responses:
        '200':
          description: 'patient prediction- healthy, suspect, or pathological'
          content:
            application/json:
	     schema:
              type: string
	'405': 
	  description: user error, invalid input

  /download/<arg1>/<arg2>/<arg3>/<arg4>/<arg5>/<arg6>/<arg7>/<arg8>/<arg9>/<arg10>/<arg11>/
        <arg12>/<arg13>/<arg14>/<arg15>/<arg16>/<arg17>/<arg18>/<arg19>/<arg20>/<arg21>:
    get:
      tags:
        - Download
      operationId: project/download.download
      description: allows user to download decision tree with highlighted path for individual path
      responses:
        '200':
          description: 'png file with decision tree'
          content:
            application/json:
              schema:
                type: object
		properties:
		 file:
		   type: png
	'405':
	  description: user error, invalid input
    

servers:
  - url: 'http://localhost:8080/engr-222'
components:
  schemas:
    CPU:
      type: object
      required:
        - model
      properties:
        model:
          type: string
