openapi: 3.0.0
info:
  version: 1.0-oas3
  title: Fetal Health Classification
  description: >-
    Predicts whether or not a fetal patient is healthy or not.
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Delaney Hayes
    email: hayesde@iu.edu
  license:
    name: "Apache"

paths: 
  /predict/{patient_id}:
    get:
      tags:
        - PREDICT
      operationId: predict.prediction
      description: gets information through predict about fetal patient, runs model
      parameters:
        - in: path
          name: patient_id
          required: true
          schema:
            type: array
            items:
              type: number
            minItems: 1
          style: simple
          explode: true
        - in: query
          name: metadata
          schema:
            type: boolean
      responses: 
        '200':
          description: 'patient prediction- healthy, suspect, or pathological'
        '405': 
          description: 'user error, invalid input'
                 
  /download/{patient_id}:
    get:
      tags:
       - DOWNLOAD
      operationId: download.download
      parameters:
        - in: path
          name: patient_id
          required: true
          schema:
            type: array
            items:
              type: number
            minItems: 1
          style: simple
          explode: true
        - in: query
          name: metadata
          schema:
            type: boolean
      responses:
        '200':
          description: 'png file with decision tree'
        '405':
          description: 'user error, invalid input'


servers:
  - url: 'http://localhost:8080/fetal_health'
components:
  schemas:
    PREDICT:
      type: array
      required:
        - model
      properties:
        model:
          type: string
    DOWNLOAD:
      type: array
      required:
       - model
      properties:
         model: 
           type: object
